### ISSUE TITLE
클레이풀 서비스 회원가입 오류

### ISSUE THREAD

**Issue by onesup** [Clayful/clayful-ruby#1]
클레이풀 서비스에 회원 가입 하려고 할 때 잘못된 이메일 검증이 시행됩니다.
<img width="367" alt="2018-11-02 12 58 42" src="https://user-images.githubusercontent.com/298348/47893303-b43f1700-de9f-11e8-97ad-bc20910507f7.png">
하이픈에 걸려있는 것으로 보입니다.

서비스 자체의 이슈는 리파지터리가 따로 없어 이곳에 남깁니다.
감사합니다.

**Comment by Daeik** [comment]
이슈 리포트 감사합니다.

리포트해주신 부분 확인 되었으며, 수정 이후에 GitHub 프로필의 이메일로 연락드리겠습니다. ^^

서비스 전반적인 부분에 대해서는 현재 GitHub Issue를 통하실 필요 없이 바로 support@clayful.io 이메일로 남겨주시면 됩니다.

감사합니다.

**Comment by Daeik** [comment]
버그 수정되었으며, 이슈 닫도록 하겠습니다.
