### ISSUE TITLE
response data 가 nil 로 반환됩니다

### ISSUE THREAD

**Issue by say8425** [Clayful/clayful-ruby#4]
안녕하세요. 어떻게 사용해야할지 모르겠어서, 직접 라이브러리 코드를 뜯어서 사용했습니다.
그런데 제가 올바르게 사용했는지 모르겠어서 이슈 남겨드립니다.

```ruby
Clayful.config['client'] = '클라이언트키'
Clayful::Collection.count
=> Clayful::Exception: 
from /Users/penguin/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/clayful-2.2.0/lib/requester.rb:64:in `block in <class:Requester>'
```

client 로 client 키를 넘겨주면 될거라 생각하고 했는데, 에러가 발생했습니다.
그래서 코드를 보니까 client 가 최종적으로 Authorization 으로 넘겨주는 것을 발견하고,
Authorization 에 직접 client 키르 넘겨줬습니다.

```ruby
Clayful.config['Authorization'] = '클라이언트키'
Clayful::Collection.count
=> #<Clayful::Response:0x00007ffc1f678ae0
 @data=nil,
 @headers=
  {:access_control_allow_credentials=>"true",
   :access_control_expose_headers=>"WWW-Authenticate,Server-Authorization,content-currency,content-time-zone",
   :cache_control=>"no-cache",
   :content_currency=>"KRW",
   :content_encoding=>"gzip",
   :content_language=>"ko",
   :content_time_zone=>"Asia/Seoul",
   :content_type=>"application/json; charset=utf-8",
   :date=>"Mon, 20 Apr 2020 06:43:19 GMT",
   :server=>"nginx/1.14.1",
   :vary=>"origin,accept-encoding",
   :transfer_encoding=>"chunked",
   :connection=>"keep-alive"},
 @status=200>
Clayful::Collection.count.data
=> nil
```

이렇게 하니까 200 OK 가 떨어졌지만, data 가 nil 을 반환하였습니다.
혹시 잘못 호출한 코드나 있나요?
고맙습니다.

**Comment by say8425** [comment]
clayful gem 에서 사용중인 [rest-client](https://github.com/rest-client) gem 의 2.1.0 버전에,
현재 [string 이 이상하게 나오는 이슈](https://github.com/rest-client/rest-client/issues/722)가 있는데, 이것과 관련이 있어보입니다.

[이슈 코멘트](https://github.com/rest-client/rest-client/issues/722#issuecomment-566782541)에 언급된데로 `accept_encoding: '*'`를 사용하니까 정상작동 합니다.
아마도 [accept_encoding: 'gzip' 에 이슈](https://github.com/rest-client/rest-client/issues/722#issuecomment-566701051) 있는 거 같습니다.

결론적으로 아래와 같이 사용하면 작동이 됩니다.

```ruby
Clayful.config['Authorization'] = '클라이언트키'
Clayful.config['Accept-Encoding'] = '*'
Clayful::Collection.count
=> #<Clayful::Response:0x00007fcf9afb65a0
 @data={"count"=>{"raw"=>148, "formatted"=>"148", "converted"=>"148"}},
 @headers=
  {:accept_ranges=>"bytes",
   :access_control_allow_credentials=>"true",
   :access_control_expose_headers=>
    "WWW-Authenticate,Server-Authorization,content-currency,content-time-zone",
   :cache_control=>"no-cache",
   :content_currency=>"KRW",
   :content_language=>"ko",
   :content_time_zone=>"Asia/Seoul",
   :content_type=>"application/json; charset=utf-8",
   :date=>"Wed, 22 Apr 2020 11:26:06 GMT",
   :server=>"nginx/1.14.1",
   :vary=>"origin,accept-encoding",
   :content_length=>"57",
   :connection=>"keep-alive"},
 @status=200>
Clayful::Collection.count.data
=> {"count"=>{"raw"=>148, "formatted"=>"148", "converted"=>"148"}}
```

아니면 rest-client gem 2.1.0 버전에만 해당 이슈가 있어 보이므로,
[clayful.gemspec](https://github.com/Clayful/clayful-ruby/blob/master/clayful.gemspec#L20)에서 rest-client gem dependency를 2.0.x 대로 고정하는 것도 하나의 방법이 될 거 같습니다.

```ruby
s.add_runtime_dependency 'rest-client', '~> 2.0.1'
```

**Comment by Daeik** [comment]
말씀해주신 대로 2.1.0으로 업그레이드를 진행하고 디코딩 문제를 해결하거나, [2.0.1 버전으로 고정하는 방법을 감안](https://github.com/rest-client/rest-client/issues/722#issuecomment-534675162)해봐야할 것 같습니다. 내부적으로 한번 검토해보고 패칭 진행하도록 하겠습니다.

이슈 남겨주셔서 감사합니다!

**Comment by Daeik** [comment]
@say8425 리포트해주신 이슈 관련하여 수정된 `v2.2.1` 버전 릴리즈 되었습니다!

[`rest-client`를 `v2.1.0`으로 업그레이드하고, 제안해주신 `Accept-Encoding` 헤더를 `*`로 설정](https://github.com/Clayful/clayful-ruby/commit/16aed9cbac2ddbfcf7f81f29d4198f54f5268f0f)하였습니다.
